// src/renderer/js/ThemeManager.vue
<script setup>
import { Moon, Sun } from "lucide-vue-next";
import { ref } from "vue";
const themes = [
  'dark',
  'light'
]
const theme = ref(themes[0]);
const nextTheme = (nextTheme = null) => {
  if (nextTheme === null) {
    nextTheme = themes[(themes.indexOf(theme.value) + 1) % themes.length]
  }
  theme.value = nextTheme;
}
</script>
<template>
  <div :class='"theme theme--" + theme'>
    <slot></slot>
    <button class="theme-switcher" @click="() => { nextTheme(); }">
      <component :is="theme === 'light' ? Moon : Sun"></component>
    </button>
  </div>
</template>

// src/renderer/ThemeManager.tsx
import { ReactNode, useState } from "react";
import { Sun, Moon } from "lucide-react";

export interface ThemeManagerProps {
  children: ReactNode
}

interface ThemeSwitchButtonProps {
  isDark: boolean,
  onClick: () => void
}
function ThemeSwitchButton(props: ThemeSwitchButtonProps) {
    return (
      <button onClick={props.onClick} className="theme-icon">
        {props.isDark ? (<Moon/>) : (<Sun/>)}
      </button>
    )
}

export default function ThemeManager(props: ThemeManagerProps) {
  const [dark, setDark] = useState(false);

  const themeClass = (dark ? "theme--dark" : "theme--light");

  return (
    <div className={"theme-manager " + themeClass}>
      {props.children}
      <ThemeSwitchButton isDark={dark} onClick={() => setDark(!dark)}/>
    </div>
  )
}
